controller_manager:
  ros__parameters:
    update_rate: 1000 
    use_sim_time: true

    diff_drive_controller: 
      type: diff_drive_controller/DiffDriveController 
  
    joint_state_broadcaster: 
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    # Required parameters
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.6
    wheel_radius: 0.1
    
    # Recommended parameters
    base_frame_id: "base_link"
    odom_frame_id: "odom"  # Add this if using odometry
    enable_odom_tf: true  # Enable TF publishing
    
    # Tuning parameters
    use_stamped_vel: false
    publish_rate: 50.0
    update_rate: 100  # Controller-specific rate