controller_manager:
  ros__parameters:
    update_rate: 1000 

    diff_drive_controller: 
      type: diff_drive_controller/DiffDriveController 

diff_drive_controller: 
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.6
    wheel_radius: 0.1
    use_stamped_vel: false
    publish_rate: 50.0
    base_frame_id: "base_link"
    update_rate: 100